### PR TITLE
Update Russian translation, make translation JSON files load from relative path instead of absolute

### PR DESCRIPTION
**Pull request by Sovenok-Hacker**

### CODE REVIEW

**Comment by slweeb** [comment]
changes to index.html are not permitted, and your change would prevent translations from loading on local files anyway

**Comment by Sovenok-Hacker** [comment]
I don't understand, but ok

**Comment by Sovenok-Hacker** [comment]
It is simply hard to test translations

**Comment by Sovenok-Hacker** [comment]
@slweeb Ok, I have reverted it

**Comment by Sovenok-Hacker** [comment]
Thanks

**Pull request merged**
