### PR TITLE
Create Behold_the_explode_people_inator.js

### PR DESCRIPTION
**Pull request by jakob3797**
Inator

### CODE REVIEW

**Comment by jakob3797** [comment]
It is tested and works

**Comment by jakob3797** [comment]
Can someone merge its Ben 3 months

**Comment by jakob3797** [comment]
3- 4 months lol

**Comment by jakob3797** [comment]
Please just merge

**Comment by jakob3797** [comment]
Y does it take so long

**Comment by jakob3797** [comment]
lol

**Comment by DBNekonico** [comment]
For some reason Ryan hasn't been merging things since a week ago, pretty sure he's busy with something big

**Comment by jakob3797** [comment]
I bet wait  for it to be merged for 4 months lol

**Comment by jakob3797** [comment]
Bruh

**Pull request closed without merging**
