### PR TITLE
random_things.js but banana

### PR DESCRIPTION
**Pull request by PumpkinPriest**
Banana

### CODE REVIEW

**Comment by slweeb** [comment]
this has a syntax error in liquid_legend's reactions - use a code editor

**Comment by slweeb** [comment]
no "probably"s, download the repo and test it locally before submitting

**Comment by PumpkinPriest** [comment]
When I try to load mods on local versions, the mods don't work, not even working ones

**Comment by slweeb** [comment]
if index.html is in the same folder as the mods folder, you just need to type the file name into the mod manager, just "random_things.js"

**Comment by PumpkinPriest** [comment]
It's in the folder "sandboxels-main" but when I type my mod into the mod loader, the element's don't appear, I tried the same with mods that I know that work but none of the mods load

**Pull request merged**
