### PR TITLE
Update tokistuff.js

### PR DESCRIPTION
**Pull request by Chocotoki**
Ok so i removed some stuff and i might add more foods

### CODE REVIEW

**Comment by slweeb** [comment]
Is this just a copy-paste of other mods..?

**Comment by Chocotoki** [comment]
Well.. Kinda but I will update it frequently like I will add more snacks,foods,and other elements 
I might add a brownie,some cookies,sausages,and animals in my next update. This is my first  mod and I’m kinda new to this site and I needed examples and I will remove some elements… yeah…

**Comment by Chocotoki** [comment]
I’m updating rn 
if you want to save some time I’m making another commit and you could merge that commit with the main if that’s how it works

**Comment by Chocotoki** [comment]
The next update will be done soon

**Comment by Chocotoki** [comment]
Ok I edited the file

**Pull request closed without merging**
