### PR TITLE
Added mod: drugs.js

### PR DESCRIPTION
**Pull request by 0rangy**
A simple mod I'm working on do add drugs from the limited information available on the internet

### CODE REVIEW

**Comment by Cantcodeli** [comment]
Why drugs

**Comment by 0rangy** [comment]
Because people want them. I'll add fent when I convince the FBI to stop looking for me

**Comment by Angrygodzillaa** [comment]
Where?

**Comment by slweeb** [comment]
Not adding this officially. You can host it somewhere else

**Pull request closed without merging**
