### PR TITLE
Create Random_quicksands.js

### PR DESCRIPTION
**Pull request by jakob3797**
Working and tested

### CODE REVIEW

**Comment by DBNekonico** [comment]
I thought this was a good mod until I scrolled all the way to the bottom. I know what you are.

**Comment by jakob3797** [comment]
Lol

**Comment by jakob3797** [comment]
U noticed

**Comment by jakob3797** [comment]
Just ignore the duplicates

**Comment by jakob3797** [comment]
To

**Comment by slweeb** [comment]
stop spamming

**Pull request merged**
