### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by randomping298124**
just uranium 235

### CODE REVIEW

**Comment by slweeb** [comment]
This is very broken with syntax errors everywhere.

**Comment by randomping298124** [comment]
k ima just fix

**Comment by slweeb** [comment]
Still broken, are you not using a code editor? I recommend you do if you don't know JavaScript syntax. Also, multiple values are formatted wrong and would simply crash the mod. You should be testing it. Tests are not accepted here.

**Comment by DoobieRalsei** [comment]
Surprised no one closed this yet

**Comment by DBNekonico** [comment]
True, the code doesn’t even work and I’m not sure why the mod was even made

**Comment by jakob3797** [comment]
lol

**Comment by slweeb** [comment]
Not fixed

**Pull request closed without merging**
