### PR TITLE
Create .js

### PR DESCRIPTION
**Pull request by mollthecoder**
The name says it all

### CODE REVIEW

**Comment by mollthecoder** [comment]
> It's a blank file. Please make your changes constructive.

r/woosh

**Comment by ifindu19** [comment]
Here you go
https://github.com/ifindu19/sandboxels-with-.js

**Comment by slweeb** [comment]
sorry!

**Comment by mollthecoder** [comment]
I put many hours into this mod

I spent hours brainstorming

I spend hours... uhh

I spent hours!!!!!

The betrayal. The heartbreak. 




Sent: Saturday, May 20, 2023 at 8:24 PM

**Pull request closed without merging**
