### PR TITLE
oreos.js

### PR DESCRIPTION
**Pull request by Lancerman556**
I added oreos lol. gonna add a couple other things maybe. there are oreos, golden oreos, and hydrox. if you smash them, they turn into creme filling

### CODE REVIEW

**Comment by HACKERPRO908** [comment]
im really impressed @Lancerman556

**Comment by HACKERPRO908** [comment]
YO @slweeb merge this

**Comment by Lancerman556** [comment]
> im really impressed @Lancerman556

ty this is my first mod

**Comment by Lancerman556** [comment]
wait. not quite ready to be put in the game

**Comment by jakob3797** [comment]
Working but u can’t add some more to it

**Comment by DBNekonico** [comment]
i want this addedd

**Comment by jakob3797** [comment]
elements.mint_creme_filling = {
     color: "#ede7c2",
     behavior: behaviors.LIQUID,
     category: "food",
     state: "solid",
     viscosity: 10000,
     isFood: true,
     hidden: true
 };
 elements.mint_oreo = {
     color: "#f0d465",
     behavior: behaviors.POWDER,
     category: "food",
     state: "solid",
     breakInto: "mint_creme_filling",
     isFood: true,
 };
 elements.twist_and_shout = {
     color: "#302016",
     behavior: behaviors.POWDER,
     category: "food",
     state: "solid",
     breakInto: "hard_cream_filling"
 };
 elements.hard_cream_filling = {
     color: "#F9F8F2",
     behavior: behaviors.LIQUID,
     category: "food",
     state: "solid",
     viscosity: 10000,
     hidden: true
 };
 elements.head.reactions.mint_creme_filling = { elem2: null, chance:0.015 }
 elements.head.reactions.mint_oreo = { elem2: null, chance:0.01 }
 elements.head.reactions.twist_and_shout = { elem2: null, chance: 0.015 }
 elements.head.reactions.hard_cream_filling = { elem2: null, chance: 0.015 }

**Comment by jakob3797** [comment]
Example from what can be added

**Comment by slweeb** [comment]
no activity draft

**Pull request closed without merging**
